services:
  dmbackend:
    container_name: dmbackend
    build: ./backend/blog-service
    depends-on: 
      dmdatabase:
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
    ports: 8082:8082
  dmfrontend:
    container_name: dmfrontend
    depends-on: dmbackend
    build: .

  dmdatabase:
    container_name: dmdatabase
    build: ./postgres_image/
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 5000:5432