services:
  dmbackend:
    container_name: dmbackend
    build: ./backend/blog-service
    depends_on: 
      dmdatabase:
        condition: service_healthy
    env_file:
      - backend/blog-service/src/main/resources/.env
    ports: 
      - 8082:8082
  dmdatabase:
    container_name: dmdatabase
    build: ./postgres_image
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - 5000:5432
    healthcheck: 
      test: ["CMD-SHELL", "sh -c 'pg_isready -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3