datasource: h2
spring:
  application:
    name: blog-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:file:./blog-service/src/main/resources/db/h2/data
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
logging:
  level:
    org.hibernate.sql: TRACE
    org.springframework.security: TRACE

---
datasource: postgres
spring:
  config:
    activate:
      on-profile: dev
    import: optional:classpath:.env[.properties]
  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driverClassName: org.postgresql.Driver
  h2:
    console:
      enabled: false
