datasource: h2
spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:h2:file:./blog-service/src/main/resources/db/h2/data
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port: 8082
logging:
  level:
    org.springframework.security: TRACE
