#!/bin/bash

echo env vars: $POSTGRES_USER, $POSTGRES_PASSWORD

psql -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} <<-EOSQL 
    CREATE DATABASE dmblog;
    GRANT ALL PRIVILEGES ON DATABASE dmblog TO $POSTGRES_USER
EOSQL